import React from 'react';
export const metadata = {
    title: "Next hero | about",
    description: "Generated by create next app",
  };
  
const AboutPage = () => {
    return (
        <div>
            <p>About Page</p>
        </div>
    );
};

export default AboutPage;