import React from 'react';
export const metadata = {
    title: "Next hero | manage product",
    description: "Generated by create next app",
  };
  
const page = () => {
    return (
        <div>
            <p>Manage Product</p>
        </div>
    );
};

export default page;