import React from 'react';
export const metadata = {
    title: "Next hero | Add product page",
    description: "Generated by create next app",
  };
  
const AddProductPage = () => {
    return (
        <div>
            Add Product
        </div>
    );
};

export default AddProductPage;