"use client";
import Link from "next/link";
import "./globals.css";


export const metadata = {
  title: "Next hero",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  console.log("from root layout");
  return (
    <html lang="en">
      <body>
        
        {children}
        
      </body>
    </html>
  );
};

export default RootLayout;
