import React from 'react';
export const metadata = {
    title: "Next hero | dashboard",
    description: "Generated by create next app",
  };
  
const DashboardPage = () => {
    return (
        <div>
            <p>DashboardPage</p>
        </div>
    );
};

export default DashboardPage;